name: sisu-env
channels:
  - gwerbin
  - pytorch
  - numba
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - absl-py=0.8.1
  - arrow-cpp=0.13.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - boost=1.67.0
  - boost-cpp=1.68.0
  - brotli=1.0.7
  - bzip2=1.0.8
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - cython=0.29.14
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gflags=2.2.2
  - glib=2.56.2
  - glog=0.4.0
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib_metadata=1.3.0
  - intel-openmp=2019.5
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.2
  - jinja2=2.10.3
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=5.2.0
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libboost=1.67.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.7.1
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxcb=1.13
  - libxgboost=0.90
  - libxml2=2.9.9
  - lightgbm=2.3.0
  - line_profiler=2.1.2
  - llvmlite=0.31.0
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=6.0.2
  - numba=0.47.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openssl=1.1.1
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parquet-cpp=1.5.1
  - parso=0.5.2
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - ptyprocess=0.6.0
  - py-boost=1.67.0
  - py-xgboost=0.90
  - pyarrow=0.13.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - re2=2020.01.01
  - readline=7.0
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - send2trash=1.5.0
  - setuptools=44.0.0
  - sip=4.19.13
  - six=1.13.0
  - snappy=1.1.7
  - sqlite=3.30.1
  - tbb=2019.8
  - terminado=0.8.3
  - testpath=0.4.4
  - thrift-cpp=0.12.0
  - tk=8.6.8
  - torchvision=0.5.0
  - tornado=6.0.3
  - tqdm=4.41.1
  - traitlets=4.3.3
  - vowpal-wabbit=8.7.0
  - vowpalwabbit=8.7.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xgboost=0.90
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.3
  - pip:
    - aiohttp==3.6.2
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - beautifulsoup4==4.8.2
    - blist==1.3.6
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.2.2
    - colorama==0.4.3
    - filelock==3.0.12
    - flask==1.1.1
    - funcsigs==1.0.2
    - future==0.18.2
    - google==2.0.3
    - grpcio==1.26.0
    - gym==0.15.4
    - h11==0.9.0
    - httptools==0.0.13
    - idna==2.8
    - itsdangerous==1.1.0
    - lz4==3.0.2
    - multidict==4.7.4
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.1.2.30
    - packaging==20.0
    - pillow==7.0.0
    - pluggy==0.13.1
    - protobuf==3.11.2
    - psutil==5.6.7
    - py==1.8.1
    - py-spy==0.3.2
    - py4j==0.10.8.1
    - pyglet==1.3.2
    - pytest==5.3.4
    - pyyaml==5.3
    - ray==0.8.0
    - redis==3.3.11
    - setproctitle==1.1.10
    - soupsieve==1.9.5
    - svmlight-loader==0.1
    - tabulate==0.8.6
    - uvicorn==0.11.2
    - uvloop==0.14.0
    - websockets==8.1
    - werkzeug==0.16.0
    - yarl==1.4.2

